# Generated by Django 4.2.25 on 2025-11-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pasw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user',
            new_name='username',
        ),
    ]
